### ISSUE TITLE
Can we get some detailed build instructions?

### ISSUE THREAD

**Issue by ChechyLevas** [mmmovania/opencloth#12]
Something that a c++ beginner (like me) can follow.

**Comment by mmmovania** [comment]
There is nothing in it. You open VisualStudio project file and build. For other platforms you can use google search on how to build a c++ opengl program.

**Comment by joegillian** [comment]
here is how i did it on Windows:
1. Download Microsoft vcpkg. https://github.com/Microsoft/vcpkg
2. Run vcpkg.bat
3. Run cmd
4. Move to vcpkg directory
5. Run "vcpkg install glew" (can take some time because it will download cmake too.)
6. Run "vcpkg install freeglut"
7. Run "vcpkg install glm"
8. Open a project in Visual studio by double clicking .sln file. (For Example OpenCloth_implicit.sln)
9. In the solution explorer right click to project (not the solution) and select properties.
10 . On the left pane select C/C++ > General.  On the Right Pane edit "Additional Include Directories" and select the folder "vcpkg-master\installed\x86-windows\include" (there must be "GL" and "glm" folders in it.) Click Apply.
11. On the left pane select Linker > General.  On the Right Pane edit "Additional Library Directories" and select the folder "vcpkg-master\installed\x86-windows\lib"  Click Apply
12. Run the project.

**Comment by rbarkmore** [comment]
@joegillian there's an open pull request that would also make it easy to build opencloth.
