### ISSUE TITLE
WebGL demos

### ISSUE THREAD

**Issue by nyotis** [mmmovania/opencloth#7]
Nothing shows up apart from the FPS indication top-left, which comes for free.
Did you try to run those recently on a modern browser?

**Comment by mmmovania** [comment]
yep, i have to update the online repos to the local version. Need some time to organize things and update. Thanks for reminding me.

**Comment by nyotis** [comment]
no problem, looking forward to play with this!

**Comment by samiqureshi** [comment]
Sir I would also be very grateful if you could find the time to push your recent changes.
Most specifically, I want to be able to start playing around with this, but the problems with
the viewports and not being able to drag the cloth from some angles is quite a hindrance, since I 
don't understand why its happening.
Thank You

**Comment by mmmovania** [comment]
@samiqureshi indeed. Let me first update the webgl demos.

**Comment by mmmovania** [comment]
OK @nyotis, I have just pushed the basic WebGL demo. I have tried running it on all three browsers, Firefox, Chrome and IE and it works fine. Could you please give it a try and let me know how it goes?

**Comment by samiqureshi** [comment]
Works for me in Chrome and IE 10. But once again, is this supposed to have draggable edges? Because I can't seem to drag the cloth from any angle.
Thanks

**Comment by mmmovania** [comment]
No you cant  drag in this demo.

**Comment by mmmovania** [comment]
OK both webgl demos are up now. @nyotis Kindly check and then I will close this issue.

**Comment by nyotis** [comment]
cheers @mmmovania all good
